title: "DraCor Textbook"
author: "DraCorOS Team"
only_build_toc_files: true
execute:
  execute_notebooks: auto
repository:
  url: https://github.com/arojascastro/dracor-textbook
  path_to_book: .
  branch: main
html:
  use_repository_button: true
  use_issues_button: true
bibtex_bibfiles:
  - references.bib
